name: KParticle
main: com.example.particles.ParticlePlugin
Authors:
  - Korefai
Github: https://github.com/Alaysa23
version: 1.2
api-version: "1.21"
commands:
  particles:
    description: Открыть меню выбора партиклов
    usage: /particles [reload]
permissions:
  particles.reload:
    description: Разрешает перезагрузку конфигурации плагина
    default: op
